### ISSUE TITLE
Extra whitespace is being shown when the timestamp is disabled

### ISSUE THREAD

**Issue by cironunes** [detro/consoleplusplus#16]

**Comment by detro** [comment]
Can't reproduce.
If you are referring to this case for example:
```
[DEBUG - 2015-07-10T14:43:02.431Z] debug verde
[INFO  - 2015-07-10T14:43:02.432Z] info
[WARN  - 2015-07-10T14:43:02.433Z] warning blink
[ERROR - 2015-07-10T14:43:02.433Z] error
log
[INFO ] info
[WARN ] warning blink
[ERROR] error
```
Where INFO and WARN get an extra space even without timestamp, that's on purpose, so those level block in the beginning of the line are all aligned.

**Comment by cironunes** [comment]
So that's on purpose, but I would like to don't have it :smile:

**Comment by detro** [comment]
OK. So how about a PR?

You could have it as a configuration parameter that by default is disabled.
The way you set/unset it should be like the other options.

I'll reopen so you can link a PR against this.
